### ISSUE TITLE
com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.getManager()Lcom/intellij/psi/impl/PsiManagerEx; [480230d49b]

### ISSUE THREAD

**Issue by aem-intellij-plugin-error-reporter** [aem-intellij-plugin-error-reporter/auto-generated-issues-storage#20]
## Description
*No description*
## Exception
```
java.lang.NoSuchMethodError: com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.getManager()Lcom/intellij/psi/impl/PsiManagerEx;
	at co.nums.intellij.aem.htl.file.HtlFileViewProvider.cloneInner(HtlFileViewProvider.kt:33)
	at co.nums.intellij.aem.htl.file.HtlFileViewProvider.cloneInner(HtlFileViewProvider.kt:12)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.createCopy(MultiplePsiFilesPerDocumentFileViewProvider.java:145)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.createCopy(MultiplePsiFilesPerDocumentFileViewProvider.java:42)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:201)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:92)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:752)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitUnderProgress$4(DocumentCommitThread.java:533)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:556)
	at com.intellij.psi.impl.DocumentCommitThread.commitSynchronously(DocumentCommitThread.java:452)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$doCommit$0(PsiDocumentManagerBase.java:454)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.intellij.psi.impl.PsiDocumentManagerBase.doCommit(PsiDocumentManagerBase.java:466)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitDocument(PsiDocumentManagerBase.java:314)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAllDocuments(PsiDocumentManagerBase.java:239)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.writeExternal(DocumentFoldingInfo.java:208)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.writeFoldingState(CodeFoldingManagerImpl.java:350)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.writeState(PsiAwareTextEditorProvider.java:86)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.writeExternal(HistoryEntry.java:184)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.a(EditorsSplitters.java:230)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.a(EditorsSplitters.java:221)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.b(EditorsSplitters.java:201)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.writeExternal(EditorsSplitters.java:168)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getState(FileEditorManagerImpl.java:1482)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getState(FileEditorManagerImpl.java:107)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:228)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:160)
	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:46)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:352)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1451)
	at com.intellij.ide.actions.SaveAllAction.actionPerformed(SaveAllAction.java:36)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:570)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
## Error context
```
Last Action:       SaveAll
Plugin Version:    0.8.3
OS Name:           Mac OS X
Java Version:      1.8.0_112-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-171.4073.35
App Version:       2017.1.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       EditorPaste
Plugin Version:    0.8.4
OS Name:           Mac OS X
Java Version:      1.8.0_152-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-172.3317.76
App Version:       2017.2
```

**Comment by karollewandowski** [comment]
I was finally able to reproduce it and fixed it. Please update to version 0.8.5.
