### ISSUE TITLE
com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.getManager()Lcom/intellij/psi/impl/PsiManagerEx; [ce873e1277]

### ISSUE THREAD

**Issue by aem-intellij-plugin-error-reporter** [aem-intellij-plugin-error-reporter/auto-generated-issues-storage#21]
## Description
*No description*
## Exception
```
java.lang.NoSuchMethodError: com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.getManager()Lcom/intellij/psi/impl/PsiManagerEx;
	at co.nums.intellij.aem.htl.file.HtlFileViewProvider.cloneInner(HtlFileViewProvider.kt:33)
	at co.nums.intellij.aem.htl.file.HtlFileViewProvider.cloneInner(HtlFileViewProvider.kt:12)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.createCopy(MultiplePsiFilesPerDocumentFileViewProvider.java:151)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.createCopy(MultiplePsiFilesPerDocumentFileViewProvider.java:42)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:201)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:92)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:803)
	at com.intellij.psi.impl.DocumentCommitThread$6.run(DocumentCommitThread.java:581)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:597)
	at com.intellij.psi.impl.DocumentCommitThread.commitSynchronously(DocumentCommitThread.java:500)
	at com.intellij.psi.impl.PsiDocumentManagerBase$5.run(PsiDocumentManagerBase.java:435)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:898)
	at com.intellij.psi.impl.PsiDocumentManagerBase.doCommit(PsiDocumentManagerBase.java:448)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitDocument(PsiDocumentManagerBase.java:300)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAllDocuments(PsiDocumentManagerBase.java:224)
	at com.intellij.openapi.command.impl.UndoableGroup.commitAllDocuments(UndoableGroup.java:249)
	at com.intellij.openapi.command.impl.UndoableGroup.doUndoOrRedo(UndoableGroup.java:159)
	at com.intellij.openapi.command.impl.UndoableGroup.undoOrRedo(UndoableGroup.java:114)
	at com.intellij.openapi.command.impl.UndoableGroup.undo(UndoableGroup.java:96)
	at com.intellij.openapi.command.impl.Undo.performAction(Undo.java:46)
	at com.intellij.openapi.command.impl.UndoRedo.execute(UndoRedo.java:142)
	at com.intellij.openapi.command.impl.CommandMerger.undoOrRedo(CommandMerger.java:217)
	at com.intellij.openapi.command.impl.UndoManagerImpl.lambda$undoOrRedo$1(UndoManagerImpl.java:425)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
	at com.intellij.openapi.command.impl.UndoManagerImpl.undoOrRedo(UndoManagerImpl.java:437)
	at com.intellij.openapi.command.impl.UndoManagerImpl.undo(UndoManagerImpl.java:405)
	at com.intellij.ide.actions.UndoAction.perform(UndoAction.java:30)
	at com.intellij.ide.actions.UndoRedoAction.actionPerformed(UndoRedoAction.java:39)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:607)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
## Error context
```
Last Action:       OpenFile
Plugin Version:    0.8.4
OS Name:           Windows Server 2012 R2
Java Version:      1.8.0_112-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IC-162.2032.8
App Version:       2016.2.4
```

**Comment by karollewandowski** [comment]
This issue is the same as https://github.com/aem-intellij-plugin-error-reporter/auto-generated-issues-storage/issues/20

It was fixed in 0.8.5, so please update the plugin the the latest version.
