### ISSUE TITLE
org/apache/batik/dom/svg/SVGOMDocument [10e85c1f02]

### ISSUE THREAD

**Issue by aem-intellij-plugin-error-reporter** [aem-intellij-plugin-error-reporter/auto-generated-issues-storage#26]
## Description
*No description*
## Exception
```
java.lang.NoClassDefFoundError: org/apache/batik/dom/svg/SVGOMDocument
	at org.apache.batik.dom.svg.SVGDOMImplementation.createDocument(Unknown Source)
	at org.apache.batik.dom.util.SAXDocumentFactory.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(Unknown Source)
	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(Unknown Source)
	at org.apache.batik.dom.svg.SAXSVGDocumentFactory.createDocument(Unknown Source)
	at com.intellij.util.SVGLoader.<init>(SVGLoader.java:136)
	at com.intellij.util.SVGLoader.load(SVGLoader.java:120)
	at com.intellij.util.ImageLoader$ImageDesc$Type$1.load(ImageLoader.java:60)
	at com.intellij.util.ImageLoader$ImageDesc.load(ImageLoader.java:112)
	at com.intellij.util.ImageLoader$ImageDescList.load(ImageLoader.java:139)
	at com.intellij.util.ImageLoader.loadFromUrl(ImageLoader.java:302)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon$MyScaledIconsCache$2.call(IconLoader.java:573)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon$MyScaledIconsCache$2.call(IconLoader.java:570)
	at com.intellij.openapi.util.IconLoader.doWithTmpRegValue(IconLoader.java:689)
	at com.intellij.openapi.util.IconLoader.access$1500(IconLoader.java:48)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon$MyScaledIconsCache.getOrScaleIcon(IconLoader.java:570)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon$MyScaledIconsCache.getOrLoadIcon(IconLoader.java:599)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:468)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:431)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconHeight(IconLoader.java:499)
	at com.intellij.notification.impl.NotificationsManagerImpl.createBalloon(NotificationsManagerImpl.java:594)
	at com.intellij.notification.impl.NotificationsManagerImpl.createBalloon(NotificationsManagerImpl.java:316)
	at com.intellij.notification.impl.NotificationsManagerImpl.notifyByBalloon(NotificationsManagerImpl.java:266)
	at com.intellij.notification.impl.NotificationsManagerImpl.showNotification(NotificationsManagerImpl.java:183)
	at com.intellij.notification.impl.NotificationsManagerImpl.lambda$doNotify$1(NotificationsManagerImpl.java:146)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$5(StartupManagerImpl.java:396)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:398)
	at com.intellij.notification.impl.NotificationsManagerImpl.doNotify(NotificationsManagerImpl.java:151)
	at com.intellij.notification.impl.NotificationsManagerImpl.access$700(NotificationsManagerImpl.java:90)
	at com.intellij.notification.impl.NotificationsManagerImpl$MyNotificationListener.notify(NotificationsManagerImpl.java:1089)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:443)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:381)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:374)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy107.notify(Unknown Source)
	at com.intellij.notification.Notifications$Bus.doNotify(Notifications.java:75)
	at com.intellij.notification.Notifications$Bus.lambda$notify$1(Notifications.java:69)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2760)
	at com.intellij.notification.Notifications$Bus.notify(Notifications.java:69)
	at com.intellij.notification.Notification.notify(Notification.java:340)
	at co.nums.intellij.aem.settings.SetAemVersionNotifier.showVersionNotification(SetAemVersionNotifier.kt:40)
	at co.nums.intellij.aem.settings.SetAemVersionNotifier.runActivity(SetAemVersionNotifier.kt:22)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAndMeasure(StartupManagerImpl.java:176)
	at com.intellij.ide.startup.impl.StartupManagerImpl.logActivityDuration(StartupManagerImpl.java:162)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivitiesFromExtensions$1(StartupManagerImpl.java:150)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:367)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$2(StartupManagerImpl.java:182)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:296)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
## Error context
```
Last Action:       
Plugin Version:    0.8.5
OS Name:           Windows 10
Java Version:      1.8.0_152-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IC-172.3968.16
App Version:       2017.2.3
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_152-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IC-172.4574.19
App Version:       2017.2.7
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       
Plugin Version:    0.8.5
OS Name:           Windows 10
Java Version:      1.8.0_112-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-162.2228.15
App Version:       2016.2.5
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_152-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-183.5429.30
App Version:       2018.3.4
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9.1
OS Name:           Windows 10
Java Version:      1.8.0_152-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IC-183.5429.30
App Version:       2018.3.4
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9.1
OS Name:           Windows 10
Java Version:      1.8.0_202-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-191.6183.87
App Version:       2019.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_202-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-191.6183.87
App Version:       2019.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_202-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-191.6183.87
App Version:       2019.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_202-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-191.6183.87
App Version:       2019.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_202-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-191.6183.87
App Version:       2019.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_202-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-191.6183.87
App Version:       2019.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_202-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-191.6183.87
App Version:       2019.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       Android.SyncProject
Plugin Version:    0.8.5
OS Name:           Windows 7
Java Version:      1.8.0_152-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      Studio
Full Product Name: Android Studio
App Version Name:  Android Studio
Is EAP:            false
App Build:         AI-181.5540.7.32.5056338
App Version:       3.2.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       SaveAll
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_202-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-191.6183.87
App Version:       2019.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       EditorUp
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_202-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-191.6183.87
App Version:       2019.1
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
*No description*
## Error context
```
Last Action:       null
Plugin Version:    0.8.5
OS Name:           Linux
Java Version:      1.8.0_152
Java VM Vendor:    Oracle Corporation
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-182.4323.46
App Version:       2018.2.3
```

**Comment by aem-intellij-plugin-error-reporter** [comment]
## Description
test after refactoring
## Error context
```
Last Action:       EditorBackSpace
Plugin Version:    0.9.1
OS Name:           Mac OS X
Java Version:      1.8.0_202-release
Java VM Vendor:    JetBrains s.r.o
Product Name:      IDEA
Full Product Name: IntelliJ IDEA
App Version Name:  IntelliJ IDEA
Is EAP:            false
App Build:         IU-191.7141.44
App Version:       2019.1.2
```

**Comment by karollewandowski** [comment]
I can't reproduce it and it looks like IntelliJ load required SVG library too late.
Also, the plugin had a bug and all issues were appended here. Some of them could be about something else. I fixed it and changed the plugin to always include full stacktrace, not only in the first message.
